### ISSUE TITLE
First Missing Integer Python

### ISSUE THREAD

**Issue by brian-chau** [bhumikatewary/Practice-Problems#102]
I'd like to implement the following algorithm for Python:

Given an unsorted integer array, find the first missing positive integer.
Example:
Given [1,2,0] return 3,
[3,4,-1,1] return 2,
[-8, -7, -6] returns 1

Your algorithm should run in O(n) time and use constant space.

**Comment by bhumikatewary** [comment]
sure you can contribute @brian-chau
