### ISSUE TITLE
Added Binary Tree Preorder Traversal in C++

### ISSUE THREAD

**Issue by atul1510** [bhumikatewary/Practice-Problems#143]
Please assign me this issue.

**Comment by yash509** [comment]
Hello, Please assign me this issue

**Comment by atul1510** [comment]
> Hello, Please assign me this issue
This issue is already assigned to me and I have already solved this issue.

**Comment by bhumikatewary** [comment]
PR merged
@yash509 you can work on any other issue or create your own issue for code contribution
