### ISSUE TITLE
[c++] Remove Nth Node From End of List and add-two-numbers

### ISSUE THREAD

**Issue by suprakash-144** [bhumikatewary/Practice-Problems#16]

**Comment by devanshukd04** [comment]
I will like to work on this issue

**Comment by yujit2003** [comment]
can i work in this

**Comment by bhumikatewary** [comment]
@devanshukd04 @yujit2003 the issue has been resolved. You can work on any other issue or create a new issue.

**Comment by yujit2003** [comment]
> @devanshukd04 @yujit2003 the issue has been resolved. You can work on any other issue or create a new issue.

Maam i have generated new issue please assign this to me and also add hacktober fest label to it thank you
