### ISSUE TITLE
[Java] Container with most water

### ISSUE THREAD

**Issue by Spardha-hash** [bhumikatewary/Practice-Problems#19]
Please assign this issue to me.

**Comment by bhumikatewary** [comment]
okay, go ahead by forking the repo and make a PR

**Comment by k562** [comment]
Can you help me with it ,AS  i am new ,So cant able find with the "[ Java ] Container with most water "  As i cant see in  the code panel . Plz do help me

**Comment by bhumikatewary** [comment]
You have to create the directory on your own and commit the files.
Go through the contribution guidelines for more clarity.

**Comment by hraj37378** [comment]
Can you assign this issue to me .

**Comment by bhumikatewary** [comment]
PR merged, issue resolved
