### ISSUE TITLE
Find Pivot in the Array List in C++

### ISSUE THREAD

**Issue by aryananand27** [bhumikatewary/Practice-Problems#203]
@bhumikatewary Kindly assign me this issue under Hacktoberfest 2022.

**Comment by 17h4ck3r11** [comment]
Kindly Assign this issue to me.

**Comment by aryananand27** [comment]
@bhumikatewary , I want to contribute in your repository through this issue, please assign me this under Hacktoberfest 2022.

**Comment by bhumikatewary** [comment]
@rajnish254 @17h4ck3r11 since @aryananand27 has created the issue, his code would be given the priority for contribution
If the code is incorrect, the next contributor's code would be taken
