### ISSUE TITLE
Java code for array 

### ISSUE THREAD

**Issue by k562** [bhumikatewary/Practice-Problems#21]
In the Array folder ,Can i write the code  in java else you can tell me in which part should i work on  through java language .

Thank - you

**Comment by bhumikatewary** [comment]
Yes you can write java codes, but remember to commit your codes in proper directory

**Comment by Saurabhk1975** [comment]
i can write the code assign me @bhumikatewary

**Comment by bhumikatewary** [comment]
The issue has been resolved @Saurabhk1975, you can contribute on some other issue or create your own issue for a code contribution
