### ISSUE TITLE
Delete Node in a Linked List

### ISSUE THREAD

**Issue by Jyotisaini-2001** [bhumikatewary/Practice-Problems#221]
Hii, I want to contribute in this problem. 
Please assign me this issue @bhumikatewary 
thank you!!

**Comment by Kushbankey** [comment]
please assign this to me!!

**Comment by Jyotisaini-2001** [comment]
Thank you @bhumikatewary . I have added my code. Please merge my pull request.

**Comment by bhumikatewary** [comment]
pr merged
