### ISSUE TITLE
[c++] Number of 1 bits (aka hamming weights)

### ISSUE THREAD

**Issue by brian-chau** [bhumikatewary/Practice-Problems#23]
I noticed there's already an implementation in the bit manipulation folder, but I'd like to add a second implementation that uses the standard library to calculate the hamming weight of a number.

**Comment by bhumikatewary** [comment]
Edit the file which is present in the folder but do not alter the code which is already there

**Comment by Naisargika1402** [comment]
Hello maintainer,
Kindly please assign this problem to me.

**Comment by bhumikatewary** [comment]
The issue has been resolved by @brian-chau 
@Naisargika1402 you can work on any other issue or create your own issue
