### ISSUE TITLE
sum of Diagonals in a Matrix in Java

### ISSUE THREAD

**Issue by Mahikagarg09** [bhumikatewary/Practice-Problems#231]
Can you please assign me this issue?

**Comment by satyam2k3** [comment]
can u assign this to me i would like to work on this issue

**Comment by harshil-1402** [comment]
can you assign it to me please I also want on work on this issue

**Comment by yash206** [comment]
Can I work on the this issue as I had done a quite number of problems related to matrices.

**Comment by bhumikatewary** [comment]
PR merged, guys those who could not contribute the code for this problem please make another issue for a unique problem.
Hope to see your PR soon @Mahikagarg09 @satyam2k3 @harshil-1402 @yash206
