### ISSUE TITLE
Adding codes of Tree Data Structure

### ISSUE THREAD

**Issue by bhumikatewary** [bhumikatewary/Practice-Problems#29]

**Comment by hraj37378** [comment]
Yes , I can do that . I have done Data Structures and Algorithms and will be happy to contribute .

**Comment by Pushkar1853** [comment]
I have studied trees and graphs in detail, and I could also add few interesting problem and solutions, I'll also like to contribute.

**Comment by Veeno-Rai** [comment]
@bhumikatewary 
Assign this to me .I can upload a list of programs in trees data structure using cpp.

**Comment by Veeno-Rai** [comment]
@bhumikatewary 
tree algorithms committed kindly review and merge
