### ISSUE TITLE
Adding DP Problems and Solutions

### ISSUE THREAD

**Issue by bhumikatewary** [bhumikatewary/Practice-Problems#30]

**Comment by Siddhesh4501** [comment]
Can you please assign me this issue ? I can add few dp solutions.

**Comment by bhumikatewary** [comment]
sure @Siddhesh4501

**Comment by Pushkar1853** [comment]
Can you please also allow me to add a few interesting problems on dp? I have done some practice on Codeforces and could use a few problems from there.

**Comment by bhumikatewary** [comment]
okay @Pushkar1853
