### ISSUE TITLE
Notes Addition

### ISSUE THREAD

**Issue by bhumikatewary** [bhumikatewary/Practice-Problems#39]

**Comment by NikhitaBarat** [comment]
Hey, I'd love to work on this one. Could you assign this to me

**Comment by NikhitaBarat** [comment]
please elaborate this issue

**Comment by bhumikatewary** [comment]
@NikhitaBarat you can contribute you notes as documentations in the repo or provide a link of your google drive. There is a contribution for DSA notes already present in the repo, you can check that
