### ISSUE TITLE
LinkedList solutions in java

### ISSUE THREAD

**Issue by bhumikatewary** [bhumikatewary/Practice-Problems#40]

**Comment by NikhitaBarat** [comment]
Hey, I'd love to work on this one. Could you assign this to me

**Comment by Harshverma893** [comment]
I will do LinkedList problems with their solution and explanations. Please assign this issue to me.

**Comment by Harshverma893** [comment]
[`Java Linked List Practice Problem with explaination and solution`](https://github.com/bhumikatewary/Practice-Problems/pull/45) @bhumikatewary Check it out.
