### ISSUE TITLE
Math Problems and Solutions

### ISSUE THREAD

**Issue by bhumikatewary** [bhumikatewary/Practice-Problems#42]

**Comment by hemantwasthere** [comment]
Hey @bhumikatewary, I want to work on this issue

**Comment by bhumikatewary** [comment]
go ahead with your contribution @hemantwasthere

**Comment by harshil-1402** [comment]
I need to create a file under the tab new pull request right?

**Comment by bhumikatewary** [comment]
@harshil-1402 go through the contribution guide
