### ISSUE TITLE
Kruska's Minimum Spanning Tree  in C++

### ISSUE THREAD

**Issue by krrahul23** [bhumikatewary/Practice-Problems#49]
I want to add implementation of Kruskal's minimum spanning tree of a graph using C++. Please assign this task to me.

**Comment by harshil-1402** [comment]
I have done the implementation can you please merge it

**Comment by bhumikatewary** [comment]
PR merged

**Comment by harshil-1402** [comment]
hey...this repo is still in hactober fest right??
Can i still contribute in it
