### ISSUE TITLE
Implementation of Disjoint Set Union  

### ISSUE THREAD

**Issue by debapriya36** [bhumikatewary/Practice-Problems#66]
Hi @bhumikatewary, I want to add the implementation of DSU.
Can you please assign it to me?

**Comment by LakshaySK106** [comment]
Hey @bhumikatewary, 
I believe the implementation of this issue, DSU is a great match for my skills.
Can you assign it to me?

**Comment by LakshaySK106** [comment]
Also, please add hacktoberfest tag to this issue.
Thanks :)

**Comment by bhumikatewary** [comment]
@LakshaySK106 you can create your own issue or work on some other code related to your interest as this issue has been resolved.

**Comment by debapriya36** [comment]
@bhumikatewary when my contributions will appear in my HF profile?

**Comment by bhumikatewary** [comment]
I couldn't get you @debapriya36
