### ISSUE TITLE
Add binary tree maximum path sum algorithm

### ISSUE THREAD

**Issue by sparsh9** [bhumikatewary/Practice-Problems#88]
Hi @bhumikatewary, I would like to contribute binary tree maximum path sum algorithm.

**Comment by Veeno-Rai** [comment]
@bhumikatewary 
i want to contribute.
i can solve  this

**Comment by bhumikatewary** [comment]
@Veeno-Rai since @sparsh9 has already made a PR, you can contribute some other code in the repo

**Comment by bhumikatewary** [comment]
PR merged
